### ISSUE TITLE
running monitoring of reads without a watch folder leads to an error

### ISSUE THREAD

**Issue by mattloose** [LooseLab/minotourcli#21]
Here's the error:

```
No Fastq Seen
FastQ Upload Status:
Files queued/processed/skipped/time/per file:0/0/0/1604944861.2268634/0
New reads seen/uploaded/skipped:0/0/0
Traceback (most recent call last):
  File "/home/grid/GIT/minotourcli/test_env/bin/minFQ", line 11, in <module>
    load_entry_point('minFQ', 'console_scripts', 'minFQ')()
  File "/home/grid/GIT/minotourcli/minFQ/minFQ.py", line 505, in main
    sys.stdout.write(", ".join(args.WATCHLIST) + "\n")
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by Adoni5** [comment]
Fixed - no watch directory neds to be specified - it can all be driven by minKNOW now
